import { Match, Player, Staff, HistoricalMatch, Season, Team } from "@/types";

// Club team
export const clubTeam: Team = {
  id: "kil",
  name: "K.I.L",
  shortName: "K.I.L",
  logo: "/images/kil-logo.png",
};

// Opponent teams
export const vikTeam: Team = {
  id: "vik",
  name: "Vik",
  shortName: "Vik",
  logo: "https://images.fotball.no/clublogos/927.png",
};

export const jolsterTeam: Team = {
  id: "jolster",
  name: "Jølster",
  shortName: "Jølster",
  logo: undefined, // Jølster har ingen logo på fotball.no
};

export const floroTeam: Team = {
  id: "floro",
  name: "Florø",
  shortName: "Florø",
  logo: "https://images.fotball.no/clublogos/918.png",
};

export const daleTeam: Team = {
  id: "dale",
  name: "Dale",
  shortName: "Dale",
  logo: "https://images.fotball.no/clublogos/946.png",
};

export const ardalTeam: Team = {
  id: "ardal",
  name: "Årdal",
  shortName: "Årdal",
  logo: "https://images.fotball.no/clublogos/1952.png",
};

export const hoyangTeam: Team = {
  id: "hoyang",
  name: "Høyang",
  shortName: "Høyang",
  logo: "https://images.fotball.no/clublogos/924.png",
};

export const fjoraTeam: Team = {
  id: "fjora",
  name: "Fjøra",
  shortName: "Fjøra",
  logo: "https://images.fotball.no/clublogos/931.png",
};

export const forde2Team: Team = {
  id: "forde2",
  name: "Førde 2",
  shortName: "Førde 2",
  logo: "https://images.fotball.no/clublogos/952.png",
};

export const maloyTeam: Team = {
  id: "maloy",
  name: "Måløy",
  shortName: "Måløy",
  logo: "https://images.fotball.no/clublogos/3275.png",
};

export const sandaneTeam: Team = {
  id: "sandane",
  name: "Sandane",
  shortName: "Sandane",
  logo: "https://images.fotball.no/clublogos/977.png",
};

export const strynTeam: Team = {
  id: "stryn",
  name: "Stryn",
  shortName: "Stryn",
  logo: "https://images.fotball.no/clublogos/981.png",
};

export const eidTeam: Team = {
  id: "eid",
  name: "Eid",
  shortName: "Eid",
  logo: "https://images.fotball.no/clublogos/968.png",
};

// Upcoming matches - Sesong 2026
export const upcomingMatches: Match[] = [
  // NM Kvalifisering
  {
    id: "nm-2026-1",
    homeTeam: vikTeam,
    awayTeam: clubTeam,
    date: "2026-03-21",
    time: "14:00",
    venue: "Vik kunstgras",
    location: "away",
    status: "upcoming",
    fiksId: "8985091",
  },
  // 4. divisjon 2026
  {
    id: "4div-2026-1",
    homeTeam: clubTeam,
    awayTeam: jolsterTeam,
    date: "2026-04-11",
    time: "15:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980772",
  },
  {
    id: "4div-2026-2",
    homeTeam: floroTeam,
    awayTeam: clubTeam,
    date: "2026-04-18",
    time: "14:00",
    venue: "Florø stadion 11 ar",
    location: "away",
    status: "upcoming",
    fiksId: "8980779",
  },
  {
    id: "4div-2026-3",
    homeTeam: clubTeam,
    awayTeam: daleTeam,
    date: "2026-04-24",
    time: "19:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980785",
  },
  {
    id: "4div-2026-4",
    homeTeam: clubTeam,
    awayTeam: ardalTeam,
    date: "2026-05-02",
    time: "15:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980792",
  },
  {
    id: "4div-2026-5",
    homeTeam: hoyangTeam,
    awayTeam: clubTeam,
    date: "2026-05-08",
    time: "19:00",
    venue: "Sletta",
    location: "away",
    status: "upcoming",
    fiksId: "8980796",
  },
  {
    id: "4div-2026-6",
    homeTeam: clubTeam,
    awayTeam: fjoraTeam,
    date: "2026-05-16",
    time: "15:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980799",
  },
  {
    id: "4div-2026-7",
    homeTeam: forde2Team,
    awayTeam: clubTeam,
    date: "2026-05-25",
    time: "15:00",
    venue: "Hafstadparken 1",
    location: "away",
    status: "upcoming",
    fiksId: "8980806",
  },
  {
    id: "4div-2026-8",
    homeTeam: clubTeam,
    awayTeam: maloyTeam,
    date: "2026-05-30",
    time: "14:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980812",
  },
  {
    id: "4div-2026-9",
    homeTeam: sandaneTeam,
    awayTeam: clubTeam,
    date: "2026-06-13",
    time: "15:00",
    venue: "Sandane Idrettspark",
    location: "away",
    status: "upcoming",
    fiksId: "8980818",
  },
  {
    id: "4div-2026-10",
    homeTeam: clubTeam,
    awayTeam: strynTeam,
    date: "2026-06-20",
    time: "15:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980825",
  },
  {
    id: "4div-2026-11",
    homeTeam: eidTeam,
    awayTeam: clubTeam,
    date: "2026-08-08",
    time: "15:00",
    venue: "Eid idrettspark",
    location: "away",
    status: "upcoming",
    fiksId: "8980831",
  },
  {
    id: "4div-2026-12",
    homeTeam: clubTeam,
    awayTeam: floroTeam,
    date: "2026-08-15",
    time: "15:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980838",
  },
  {
    id: "4div-2026-13",
    homeTeam: daleTeam,
    awayTeam: clubTeam,
    date: "2026-08-21",
    time: "19:00",
    venue: "Dingemoen idrettspark 11 ar",
    location: "away",
    status: "upcoming",
    fiksId: "8980844",
  },
  {
    id: "4div-2026-14",
    homeTeam: jolsterTeam,
    awayTeam: clubTeam,
    date: "2026-08-29",
    time: "15:00",
    venue: "Skei stadion naturgras",
    location: "away",
    status: "upcoming",
    fiksId: "8980851",
  },
  {
    id: "4div-2026-15",
    homeTeam: ardalTeam,
    awayTeam: clubTeam,
    date: "2026-09-05",
    time: "15:00",
    venue: "Jotun stadion",
    location: "away",
    status: "upcoming",
    fiksId: "8980857",
  },
  {
    id: "4div-2026-16",
    homeTeam: clubTeam,
    awayTeam: hoyangTeam,
    date: "2026-09-12",
    time: "15:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980864",
  },
  {
    id: "4div-2026-17",
    homeTeam: fjoraTeam,
    awayTeam: clubTeam,
    date: "2026-09-19",
    time: "15:00",
    venue: "Fosshaugane Campus",
    location: "away",
    status: "upcoming",
    fiksId: "8980870",
  },
  {
    id: "4div-2026-18",
    homeTeam: clubTeam,
    awayTeam: forde2Team,
    date: "2026-09-26",
    time: "15:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980877",
  },
  {
    id: "4div-2026-19",
    homeTeam: maloyTeam,
    awayTeam: clubTeam,
    date: "2026-10-03",
    time: "15:00",
    venue: "Skavøypoll Stadion",
    location: "away",
    status: "upcoming",
    fiksId: "8980883",
  },
  {
    id: "4div-2026-20",
    homeTeam: clubTeam,
    awayTeam: sandaneTeam,
    date: "2026-10-10",
    time: "14:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980890",
  },
  {
    id: "4div-2026-21",
    homeTeam: strynTeam,
    awayTeam: clubTeam,
    date: "2026-10-17",
    time: "14:00",
    venue: "Stryn stadion",
    location: "away",
    status: "upcoming",
    fiksId: "8980896",
  },
  {
    id: "4div-2026-22",
    homeTeam: clubTeam,
    awayTeam: eidTeam,
    date: "2026-10-24",
    time: "14:00",
    venue: "Kaupanger Idrettspark hovudbane 11 ar",
    location: "home",
    status: "upcoming",
    fiksId: "8980903",
  },
];

// Players - Statistikk for Kaupanger (totalt for klubben)
export const players: Player[] = [
  // Keepers
  {
    id: "p1",
    firstName: "Iver",
    lastName: "Sætre Systad",
    position: "keeper",
    positionLabel: "Keeper",
    number: 1,
    appearances: 19,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  // Defenders
  {
    id: "p3",
    firstName: "Håvard",
    lastName: "Grøteide",
    position: "defender",
    positionLabel: "Forsvar",
    number: 6,
    appearances: 20,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p4",
    firstName: "Leif Andrik",
    lastName: "Teigen",
    position: "defender",
    positionLabel: "Forsvar",
    number: 5,
    appearances: 19,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p5",
    firstName: "Kim Andre",
    lastName: "Dyrdal Stokke",
    position: "defender",
    positionLabel: "Forsvar",
    number: 7,
    appearances: 5,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p6",
    firstName: "Eirik Hellebust",
    lastName: "Menes",
    position: "defender",
    positionLabel: "Forsvar",
    number: 3,
    appearances: 14,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p7",
    firstName: "Preben Bruflot",
    lastName: "Undeland",
    position: "defender",
    positionLabel: "Forsvar",
    number: 21,
    appearances: 16,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p11",
    firstName: "Kristoffer",
    lastName: "Dalaker",
    position: "defender",
    positionLabel: "Forsvar",
    number: 14,
    appearances: 16,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  // Midfielders
  {
    id: "p8",
    firstName: "Karsten",
    lastName: "Bjelde",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 10,
    appearances: 15,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p9",
    firstName: "Rune Vatnamot",
    lastName: "Åberge",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 4,
    appearances: 21,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p10",
    firstName: "Christopher Skjær",
    lastName: "Brugrand",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 18,
    appearances: 10,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p12",
    firstName: "Aleksander Belland",
    lastName: "Eriksen",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 23,
    appearances: 10,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  // Forwards
  {
    id: "p14",
    firstName: "Jørgen",
    lastName: "Dalaker",
    position: "forward",
    positionLabel: "Angrep",
    number: 8,
    appearances: 18,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p15",
    firstName: "Jens",
    lastName: "Mo",
    position: "forward",
    positionLabel: "Angrep",
    number: 19,
    appearances: 5,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p16",
    firstName: "Sindre Åmot",
    lastName: "Alme",
    position: "forward",
    positionLabel: "Angrep",
    number: 11,
    appearances: 3,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  // Nye spelarar 2026
  {
    id: "p18",
    firstName: "Iver",
    lastName: "Harberg",
    position: "forward",
    positionLabel: "Angrep",
    number: 12,
    appearances: 0,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p19",
    firstName: "Henning",
    lastName: "Bruflat",
    position: "defender",
    positionLabel: "Forsvar",
    number: 13,
    appearances: 0,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p20",
    firstName: "Nalawi Foto",
    lastName: "Solomon",
    position: "forward",
    positionLabel: "Angrep",
    number: 15,
    appearances: 3,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p21",
    firstName: "Sverre Liaseth",
    lastName: "Vinjevoll",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 17,
    appearances: 0,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p22",
    firstName: "Jesper Sæverud",
    lastName: "Økland",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 18,
    appearances: 0,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
];

// Staff
export const staff: Staff[] = [
  {
    id: "s1",
    firstName: "Håvard",
    lastName: "Grøteide",
    role: "head_coach",
    roleLabel: "Trener",
    fiksId: "3657378",
    roles: [
      {
        title: "Trener",
        team: "Kaupanger Menn 5er 1",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Trener",
        team: "Kaupanger Menn 1",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Spiller",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Futsalspiller",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
    ],
  },
  {
    id: "s2",
    firstName: "Asbjørn",
    lastName: "Dale",
    role: "manager",
    roleLabel: "Kontaktperson",
    fiksId: "4038970",
    roles: [
      {
        title: "Kontaktperson",
        team: "Kaupanger Menn 1",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "FIKS-ansvarleg",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Ansvarleg lagpåmelding",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Spiller",
        club: "Stubban Fotballklubb",
        krets: "NFF Trøndelag",
      },
    ],
  },
];

// Seasons
export const seasons: Season[] = [
  { id: "2026", label: "Sesong 2026", startYear: 2026, endYear: 2026 },
  { id: "2025", label: "Sesong 2025", startYear: 2025, endYear: 2025 },
  { id: "2024", label: "Sesong 2024", startYear: 2024, endYear: 2024 },
];

// Historical matches / Results - 2025 season
export const historicalMatches: HistoricalMatch[] = [
  // 2025 season matches
  {
    id: "h1",
    homeTeam: { id: "sogndal2", name: "Sogndal 2", shortName: "Sogndal 2" },
    awayTeam: clubTeam,
    date: "2025-04-12",
    venue: "Fosshaugane Campus",
    venueType: "away",
    homeScore: 3,
    awayScore: 1,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706408",
  },
  {
    id: "h2",
    homeTeam: clubTeam,
    awayTeam: { id: "sandane", name: "Sandane", shortName: "Sandane" },
    date: "2025-04-26",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 2,
    awayScore: 1,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "win",
    season: "2025",
    fiksId: "8706414",
  },
  {
    id: "h3",
    homeTeam: { id: "hoyang", name: "Høyang", shortName: "Høyang" },
    awayTeam: clubTeam,
    date: "2025-05-03",
    venue: "Sletta kunstgras",
    venueType: "away",
    homeScore: 4,
    awayScore: 1,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706419",
  },
  {
    id: "h4",
    homeTeam: clubTeam,
    awayTeam: { id: "stryn", name: "Stryn", shortName: "Stryn" },
    date: "2025-05-10",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 5,
    awayScore: 4,
    halfTimeHome: 1,
    halfTimeAway: 3,
    result: "win",
    season: "2025",
    fiksId: "8706429",
  },
  {
    id: "h5",
    homeTeam: { id: "ardal", name: "Årdal", shortName: "Årdal" },
    awayTeam: clubTeam,
    date: "2025-05-16",
    venue: "Jotun stadion",
    venueType: "away",
    homeScore: 1,
    awayScore: 0,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706436",
  },
  {
    id: "h6",
    homeTeam: { id: "eid", name: "Eid", shortName: "Eid" },
    awayTeam: clubTeam,
    date: "2025-05-24",
    venue: "Eid stadion",
    venueType: "away",
    homeScore: 3,
    awayScore: 2,
    halfTimeHome: 2,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706441",
  },
  {
    id: "h7",
    homeTeam: clubTeam,
    awayTeam: { id: "dale", name: "Dale", shortName: "Dale" },
    date: "2025-05-29",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 2,
    awayScore: 2,
    halfTimeHome: 2,
    halfTimeAway: 2,
    result: "draw",
    season: "2025",
    fiksId: "8706446",
  },
  {
    id: "h8",
    homeTeam: { id: "bremanger", name: "Bremanger", shortName: "Bremanger" },
    awayTeam: clubTeam,
    date: "2025-06-07",
    venue: "Bremanger stadion",
    venueType: "away",
    homeScore: 1,
    awayScore: 3,
    halfTimeHome: 0,
    halfTimeAway: 1,
    result: "win",
    season: "2025",
    fiksId: "8706463",
  },
  {
    id: "h9",
    homeTeam: clubTeam,
    awayTeam: { id: "forde2", name: "Førde 2", shortName: "Førde 2" },
    date: "2025-06-15",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 4,
    awayScore: 3,
    result: "win",
    season: "2025",
    fiksId: "8706458",
  },
  {
    id: "h10",
    homeTeam: { id: "jolster", name: "Jølster", shortName: "Jølster" },
    awayTeam: clubTeam,
    date: "2025-06-18",
    venue: "Skei stadion naturgras",
    venueType: "away",
    homeScore: 4,
    awayScore: 1,
    result: "loss",
    season: "2025",
    fiksId: "8706452",
  },
  {
    id: "h11",
    homeTeam: clubTeam,
    awayTeam: { id: "floro", name: "Florø", shortName: "Florø" },
    date: "2025-06-28",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 1,
    awayScore: 3,
    result: "loss",
    season: "2025",
    fiksId: "8706470",
  },
  {
    id: "h12",
    homeTeam: clubTeam,
    awayTeam: { id: "sogndal2", name: "Sogndal 2", shortName: "Sogndal 2" },
    date: "2025-08-11",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 0,
    awayScore: 1,
    result: "loss",
    season: "2025",
    fiksId: "8706474",
  },
  {
    id: "h13",
    homeTeam: { id: "sandane", name: "Sandane", shortName: "Sandane" },
    awayTeam: clubTeam,
    date: "2025-08-16",
    venue: "Sandane Idrettspark",
    venueType: "away",
    homeScore: 4,
    awayScore: 2,
    result: "loss",
    season: "2025",
    fiksId: "8706480",
  },
  {
    id: "h14",
    homeTeam: clubTeam,
    awayTeam: { id: "hoyang", name: "Høyang", shortName: "Høyang" },
    date: "2025-08-23",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 0,
    awayScore: 5,
    result: "loss",
    season: "2025",
    fiksId: "8706485",
  },
  {
    id: "h15",
    homeTeam: { id: "stryn", name: "Stryn", shortName: "Stryn" },
    awayTeam: clubTeam,
    date: "2025-08-30",
    venue: "Stryn stadion",
    venueType: "away",
    homeScore: 4,
    awayScore: 1,
    result: "loss",
    season: "2025",
    fiksId: "8706495",
  },
  {
    id: "h16",
    homeTeam: clubTeam,
    awayTeam: { id: "ardal", name: "Årdal", shortName: "Årdal" },
    date: "2025-09-05",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 3,
    awayScore: 4,
    result: "loss",
    season: "2025",
    fiksId: "8706502",
  },
  {
    id: "h17",
    homeTeam: clubTeam,
    awayTeam: { id: "eid", name: "Eid", shortName: "Eid" },
    date: "2025-09-13",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 0,
    awayScore: 3,
    result: "loss",
    season: "2025",
    fiksId: "8706507",
  },
  {
    id: "h18",
    homeTeam: { id: "dale", name: "Dale", shortName: "Dale" },
    awayTeam: clubTeam,
    date: "2025-09-19",
    venue: "Dingemoen Idrettspark",
    venueType: "away",
    homeScore: 0,
    awayScore: 1,
    result: "win",
    season: "2025",
    fiksId: "8706512",
  },
  {
    id: "h19",
    homeTeam: { id: "floro", name: "Florø", shortName: "Florø" },
    awayTeam: clubTeam,
    date: "2025-09-27",
    venue: "Florø stadion",
    venueType: "away",
    homeScore: 6,
    awayScore: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706536",
  },
  {
    id: "h20",
    homeTeam: clubTeam,
    awayTeam: { id: "bremanger", name: "Bremanger", shortName: "Bremanger" },
    date: "2025-10-04",
    venue: "Hafstadparken 1",
    venueType: "home",
    homeScore: 9,
    awayScore: 0,
    result: "win",
    season: "2025",
    fiksId: "8706529",
  },
  {
    id: "h21",
    homeTeam: { id: "forde2", name: "Førde 2", shortName: "Førde 2" },
    awayTeam: clubTeam,
    date: "2025-10-11",
    venue: "Hafstadparken 1",
    venueType: "away",
    homeScore: 2,
    awayScore: 2,
    result: "draw",
    season: "2025",
    fiksId: "8706524",
  },
  {
    id: "h22",
    homeTeam: clubTeam,
    awayTeam: { id: "jolster", name: "Jølster", shortName: "Jølster" },
    date: "2025-10-18",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 1,
    awayScore: 2,
    result: "loss",
    season: "2025",
    fiksId: "8706518",
  },
];

// Group players by position
export const getPlayersByPosition = () => {
  return {
    keepers: players.filter((p) => p.position === "keeper"),
    defenders: players.filter((p) => p.position === "defender"),
    midfielders: players.filter((p) => p.position === "midfielder"),
    forwards: players.filter((p) => p.position === "forward"),
  };
};

// Get results by season
export const getResultsBySeason = (seasonId: string) => {
  return historicalMatches.filter((m) => m.season === seasonId);
};
