import { Match, Player, Staff, HistoricalMatch, Season, Team } from "@/types";

// Club team
export const clubTeam: Team = {
  id: "kil",
  name: "K.I.L",
  shortName: "K.I.L",
  logo: "/images/kil-logo.png",
};

// Opponent teams
export const vikTeam: Team = {
  id: "vik",
  name: "Vik",
  shortName: "Vik",
  logo: "https://images.fotball.no/clublogos/927.png",
};

// Upcoming matches - NM Kvalifisering 2026
export const upcomingMatches: Match[] = [
  {
    id: "nm-2026-1",
    homeTeam: vikTeam,
    awayTeam: clubTeam,
    date: "2026-03-21",
    time: "14:00",
    venue: "Vik kunstgras",
    location: "away",
    status: "upcoming",
  },
];

// Players
export const players: Player[] = [
  // Keepers
  {
    id: "p1",
    firstName: "Iver",
    lastName: "Sætre Systad",
    position: "keeper",
    positionLabel: "Keeper",
    number: 1,
    appearances: 17,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p2",
    firstName: "Håkon",
    lastName: "Wathne",
    position: "defender",
    positionLabel: "Forsvar",
    number: 12,
    appearances: 11,
    goals: 0,
    yellowCards: 4,
    redCards: 0,
  },
  // Defenders
  {
    id: "p3",
    firstName: "Håvard",
    lastName: "Grøteide",
    position: "defender",
    positionLabel: "Forsvar",
    number: 4,
    appearances: 19,
    goals: 1,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: "p4",
    firstName: "Leif Andrik",
    lastName: "Teigen",
    position: "defender",
    positionLabel: "Forsvar",
    number: 5,
    appearances: 18,
    goals: 2,
    yellowCards: 3,
    redCards: 0,
  },
  {
    id: "p5",
    firstName: "Kim Andre",
    lastName: "Dyrdal Stokke",
    position: "defender",
    positionLabel: "Forsvar",
    number: 3,
    appearances: 15,
    goals: 2,
    yellowCards: 2,
    redCards: 1,
  },
  {
    id: "p6",
    firstName: "Eirik Hellebust",
    lastName: "Menes",
    position: "defender",
    positionLabel: "Forsvar",
    number: 2,
    appearances: 15,
    goals: 0,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p7",
    firstName: "Preben Bruflot",
    lastName: "Undeland",
    position: "defender",
    positionLabel: "Forsvar",
    number: 6,
    appearances: 11,
    goals: 1,
    yellowCards: 1,
    redCards: 0,
  },
  // Midfielders
  {
    id: "p8",
    firstName: "Karsten",
    lastName: "Bjelde",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 10,
    appearances: 19,
    goals: 29,
    yellowCards: 2,
    redCards: 0,
  },
  {
    id: "p9",
    firstName: "Rune Vatnamot",
    lastName: "Åberge",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 8,
    appearances: 19,
    goals: 2,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p10",
    firstName: "Christopher Skjær",
    lastName: "Brugrand",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 7,
    appearances: 12,
    goals: 1,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p11",
    firstName: "Kristoffer",
    lastName: "Dalaker",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 14,
    appearances: 11,
    goals: 2,
    yellowCards: 3,
    redCards: 1,
  },
  {
    id: "p12",
    firstName: "Aleksander Belland",
    lastName: "Eriksen",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 16,
    appearances: 10,
    goals: 3,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p13",
    firstName: "Jo Nikolai",
    lastName: "Haukås",
    position: "midfielder",
    positionLabel: "Midtbane",
    number: 17,
    appearances: 10,
    goals: 1,
    yellowCards: 0,
    redCards: 0,
  },
  // Forwards
  {
    id: "p14",
    firstName: "Jørgen",
    lastName: "Dalaker",
    position: "forward",
    positionLabel: "Angrep",
    number: 9,
    appearances: 20,
    goals: 7,
    yellowCards: 5,
    redCards: 1,
  },
  {
    id: "p15",
    firstName: "Jens",
    lastName: "Mo",
    position: "forward",
    positionLabel: "Angrep",
    number: 11,
    appearances: 13,
    goals: 4,
    yellowCards: 0,
    redCards: 0,
  },
  {
    id: "p16",
    firstName: "Erlend",
    lastName: "Loftesnes",
    position: "forward",
    positionLabel: "Angrep",
    number: 18,
    appearances: 12,
    goals: 3,
    yellowCards: 1,
    redCards: 0,
  },
  {
    id: "p17",
    firstName: "Sindre Åmot",
    lastName: "Alme",
    position: "forward",
    positionLabel: "Angrep",
    number: 19,
    appearances: 11,
    goals: 3,
    yellowCards: 0,
    redCards: 0,
  },
];

// Staff
export const staff: Staff[] = [
  {
    id: "s1",
    firstName: "Håvard",
    lastName: "Grøteide",
    role: "head_coach",
    roleLabel: "Trener",
    fiksId: "3657378",
    roles: [
      {
        title: "Trener",
        team: "Kaupanger Menn 5er 1",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Trener",
        team: "Kaupanger Menn 1",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Spiller",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Futsalspiller",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
    ],
  },
  {
    id: "s2",
    firstName: "Asbjørn",
    lastName: "Dale",
    role: "manager",
    roleLabel: "Kontaktperson",
    fiksId: "4038970",
    roles: [
      {
        title: "Kontaktperson",
        team: "Kaupanger Menn 1",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "FIKS-ansvarleg",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Ansvarleg lagpåmelding",
        club: "Kaupanger Idrettslag",
        krets: "NFF Sogn og Fjordane",
      },
      {
        title: "Spiller",
        club: "Stubban Fotballklubb",
        krets: "NFF Trøndelag",
      },
    ],
  },
];

// Seasons
export const seasons: Season[] = [
  { id: "2025", label: "Sesong 2025", startYear: 2025, endYear: 2025 },
  { id: "2024", label: "Sesong 2024", startYear: 2024, endYear: 2024 },
];

// Historical matches / Results - 2025 season
export const historicalMatches: HistoricalMatch[] = [
  // 2025 season matches
  {
    id: "h1",
    homeTeam: { id: "sogndal2", name: "Sogndal 2", shortName: "Sogndal 2" },
    awayTeam: clubTeam,
    date: "2025-04-12",
    venue: "Fosshaugane Campus",
    venueType: "away",
    homeScore: 3,
    awayScore: 1,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706408",
  },
  {
    id: "h2",
    homeTeam: clubTeam,
    awayTeam: { id: "sandane", name: "Sandane", shortName: "Sandane" },
    date: "2025-04-26",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 2,
    awayScore: 1,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "win",
    season: "2025",
    fiksId: "8706414",
  },
  {
    id: "h3",
    homeTeam: { id: "hoyang", name: "Høyang", shortName: "Høyang" },
    awayTeam: clubTeam,
    date: "2025-05-03",
    venue: "Sletta kunstgras",
    venueType: "away",
    homeScore: 4,
    awayScore: 1,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706419",
  },
  {
    id: "h4",
    homeTeam: clubTeam,
    awayTeam: { id: "stryn", name: "Stryn", shortName: "Stryn" },
    date: "2025-05-10",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 5,
    awayScore: 4,
    halfTimeHome: 1,
    halfTimeAway: 3,
    result: "win",
    season: "2025",
    fiksId: "8706429",
  },
  {
    id: "h5",
    homeTeam: { id: "ardal", name: "Årdal", shortName: "Årdal" },
    awayTeam: clubTeam,
    date: "2025-05-16",
    venue: "Jotun stadion",
    venueType: "away",
    homeScore: 1,
    awayScore: 0,
    halfTimeHome: 1,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706436",
  },
  {
    id: "h6",
    homeTeam: { id: "eid", name: "Eid", shortName: "Eid" },
    awayTeam: clubTeam,
    date: "2025-05-24",
    venue: "Eid stadion",
    venueType: "away",
    homeScore: 3,
    awayScore: 2,
    halfTimeHome: 2,
    halfTimeAway: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706441",
  },
  {
    id: "h7",
    homeTeam: clubTeam,
    awayTeam: { id: "dale", name: "Dale", shortName: "Dale" },
    date: "2025-05-29",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 2,
    awayScore: 2,
    halfTimeHome: 2,
    halfTimeAway: 2,
    result: "draw",
    season: "2025",
    fiksId: "8706446",
  },
  {
    id: "h8",
    homeTeam: { id: "bremanger", name: "Bremanger", shortName: "Bremanger" },
    awayTeam: clubTeam,
    date: "2025-06-07",
    venue: "Bremanger stadion",
    venueType: "away",
    homeScore: 1,
    awayScore: 3,
    halfTimeHome: 0,
    halfTimeAway: 1,
    result: "win",
    season: "2025",
    fiksId: "8706463",
  },
  {
    id: "h9",
    homeTeam: clubTeam,
    awayTeam: { id: "forde2", name: "Førde 2", shortName: "Førde 2" },
    date: "2025-06-15",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 4,
    awayScore: 3,
    result: "win",
    season: "2025",
    fiksId: "8706458",
  },
  {
    id: "h10",
    homeTeam: { id: "jolster", name: "Jølster", shortName: "Jølster" },
    awayTeam: clubTeam,
    date: "2025-06-18",
    venue: "Skei stadion naturgras",
    venueType: "away",
    homeScore: 4,
    awayScore: 1,
    result: "loss",
    season: "2025",
    fiksId: "8706452",
  },
  {
    id: "h11",
    homeTeam: clubTeam,
    awayTeam: { id: "floro", name: "Florø", shortName: "Florø" },
    date: "2025-06-28",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 1,
    awayScore: 3,
    result: "loss",
    season: "2025",
    fiksId: "8706470",
  },
  {
    id: "h12",
    homeTeam: clubTeam,
    awayTeam: { id: "sogndal2", name: "Sogndal 2", shortName: "Sogndal 2" },
    date: "2025-08-11",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 0,
    awayScore: 1,
    result: "loss",
    season: "2025",
    fiksId: "8706474",
  },
  {
    id: "h13",
    homeTeam: { id: "sandane", name: "Sandane", shortName: "Sandane" },
    awayTeam: clubTeam,
    date: "2025-08-16",
    venue: "Sandane Idrettspark",
    venueType: "away",
    homeScore: 4,
    awayScore: 2,
    result: "loss",
    season: "2025",
    fiksId: "8706480",
  },
  {
    id: "h14",
    homeTeam: clubTeam,
    awayTeam: { id: "hoyang", name: "Høyang", shortName: "Høyang" },
    date: "2025-08-23",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 0,
    awayScore: 5,
    result: "loss",
    season: "2025",
    fiksId: "8706485",
  },
  {
    id: "h15",
    homeTeam: { id: "stryn", name: "Stryn", shortName: "Stryn" },
    awayTeam: clubTeam,
    date: "2025-08-30",
    venue: "Stryn stadion",
    venueType: "away",
    homeScore: 4,
    awayScore: 1,
    result: "loss",
    season: "2025",
    fiksId: "8706495",
  },
  {
    id: "h16",
    homeTeam: clubTeam,
    awayTeam: { id: "ardal", name: "Årdal", shortName: "Årdal" },
    date: "2025-09-05",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 3,
    awayScore: 4,
    result: "loss",
    season: "2025",
    fiksId: "8706502",
  },
  {
    id: "h17",
    homeTeam: clubTeam,
    awayTeam: { id: "eid", name: "Eid", shortName: "Eid" },
    date: "2025-09-13",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 0,
    awayScore: 3,
    result: "loss",
    season: "2025",
    fiksId: "8706507",
  },
  {
    id: "h18",
    homeTeam: { id: "dale", name: "Dale", shortName: "Dale" },
    awayTeam: clubTeam,
    date: "2025-09-19",
    venue: "Dingemoen Idrettspark",
    venueType: "away",
    homeScore: 0,
    awayScore: 1,
    result: "win",
    season: "2025",
    fiksId: "8706512",
  },
  {
    id: "h19",
    homeTeam: { id: "floro", name: "Florø", shortName: "Florø" },
    awayTeam: clubTeam,
    date: "2025-09-27",
    venue: "Florø stadion",
    venueType: "away",
    homeScore: 6,
    awayScore: 0,
    result: "loss",
    season: "2025",
    fiksId: "8706536",
  },
  {
    id: "h20",
    homeTeam: clubTeam,
    awayTeam: { id: "bremanger", name: "Bremanger", shortName: "Bremanger" },
    date: "2025-10-04",
    venue: "Hafstadparken 1",
    venueType: "home",
    homeScore: 9,
    awayScore: 0,
    result: "win",
    season: "2025",
    fiksId: "8706529",
  },
  {
    id: "h21",
    homeTeam: { id: "forde2", name: "Førde 2", shortName: "Førde 2" },
    awayTeam: clubTeam,
    date: "2025-10-11",
    venue: "Hafstadparken 1",
    venueType: "away",
    homeScore: 2,
    awayScore: 2,
    result: "draw",
    season: "2025",
    fiksId: "8706524",
  },
  {
    id: "h22",
    homeTeam: clubTeam,
    awayTeam: { id: "jolster", name: "Jølster", shortName: "Jølster" },
    date: "2025-10-18",
    venue: "Kaupanger Idrettspark",
    venueType: "home",
    homeScore: 1,
    awayScore: 2,
    result: "loss",
    season: "2025",
    fiksId: "8706518",
  },
];

// Group players by position
export const getPlayersByPosition = () => {
  return {
    keepers: players.filter((p) => p.position === "keeper"),
    defenders: players.filter((p) => p.position === "defender"),
    midfielders: players.filter((p) => p.position === "midfielder"),
    forwards: players.filter((p) => p.position === "forward"),
  };
};

// Filter matches
export const filterMatches = (filter: "all" | "home" | "away") => {
  if (filter === "all") return upcomingMatches;
  return upcomingMatches.filter((m) => m.location === filter);
};

// Get results by season
export const getResultsBySeason = (seasonId: string) => {
  return historicalMatches.filter((m) => m.season === seasonId);
};
